services:
  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_SECURE_COOKIE=false
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_EDITOR_BASE_URL=http://localhost:5678/
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - SHEET_NAME_MAIN=${SHEET_NAME_MAIN}
      - SHEET_NAME_SECONDARY=${SHEET_NAME_SECONDARY}
      - TELEGRAM_BOT_TOKEN_NUTRIENT=${TELEGRAM_BOT_TOKEN_NUTRIENT}
      - TELEGRAM_BOT_TOKEN_EXPENSE=${TELEGRAM_BOT_TOKEN_EXPENSE}
      - SPREADSHEET_ID_EXPENSE=${SPREADSHEET_ID_EXPENSE}
      - SPREADSHEET_ID_NUTRIENT=${SPREADSHEET_ID_NUTRIENT}
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http n8n:5678
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - n8n

volumes:
  n8n_data:
